export type {
  AppUpdateInfo,
  AppUpdateRefKind,
  AppUpdateResult,
  McpConfig,
  McpServerEntry,
  McpToolPreview,
  McpTransport,
  PluginCatalogItem,
  PluginConfigFieldSchema,
  PluginConfigFieldType,
  PluginConfigGroupSchema,
  PluginConfigI18nMap,
  PluginConfigOption,
  PluginConfigSaveResult,
  PluginInstallInput,
  PluginManifest,
  PluginSlotId,
  PluginUIDetail,
  PluginUIPage,
  PluginUIPageKind,
} from "../../shared/platform/types";
export { isPluginSlotId, pluginSlotIds } from "../../shared/plugin/slotIds";
