export type {
  AppUpdateInfo,
  AppUpdateRefKind,
  AppUpdateResult,
  McpConfig,
  McpServerEntry,
  McpToolPreview,
  McpTransport,
  PluginCatalogItem,
  PluginConfigAction,
  PluginConfigActionVariant,
  PluginConfigActionResult,
  PluginConfigFieldSchema,
  PluginConfigFieldType,
  PluginConfigGroupSchema,
  PluginConfigI18nMap,
  PluginConfigOption,
  PluginConfigSaveResult,
  PluginInstallInput,
  PluginLocalScanResult,
  PluginManifest,
  PluginSubmissionClipboardResult,
  PluginSubmissionInput,
  PluginSubmissionIssueResult,
  PluginSubmissionPayload,
  PluginSubmissionValidationResult,
  PluginSlotId,
  PluginSlotActionResult,
  PluginSlotContribution,
  PluginSlotContributionIcon,
  PluginSlotContributionVariant,
  PluginUIDetail,
  PluginUIPage,
  PluginUIPageKind,
} from "../../shared/platform/types";
export { isPluginSlotId, pluginSlotIds } from "../../shared/plugin/slotIds";
