import type { ChatThemePayload } from "../theme/chatChromeTheme";
import type { ChatThemeManifest, ChatThemeSummary } from "../theme/chatTheme";
import { DEFAULT_CHARACTER_COLOR } from "../constants";
import type {
  AppConfig,
  ChatLaunchPayload,
  ChatSnapshot,
  McpConfig,
  McpToolPreview,
  PluginCatalogItem,
  PluginManifest,
  TemplateSummary,
} from "./types";

export const sampleConfig: AppConfig = {
  adapter_catalog: {
    asr: [
      {
        label: "Vosk",
        schema: {
          model_path: {
            default: "./assets/system/models/vosk-model-small-cn-0.22",
            label: "Vosk model path",
            type: "str",
          },
        },
        value: "vosk",
      },
      { label: "faster-whisper", schema: {}, value: "faster_whisper" },
      { label: "RealtimeSTT", schema: {}, value: "realtime_stt" },
    ],
    llm: [
      {
        label: "Deepseek",
        schema: {
          reasoning_effort: {
            choices: ["high", "max"],
            default: "high",
            label: "思考强度 (reasoning_effort)",
            type: "str",
          },
          thinking_enabled: {
            default: false,
            label: "思考模式",
            type: "bool",
          },
        },
        value: "Deepseek",
      },
      { label: "ChatGPT", schema: {}, value: "ChatGPT" },
      { label: "Gemini", schema: {}, value: "Gemini" },
      { label: "Claude", schema: {}, value: "Claude" },
      { label: "豆包", schema: {}, value: "豆包" },
      { label: "通义千问", schema: {}, value: "通义千问" },
    ],
    t2i: [
      { label: "ComfyUI", schema: {}, value: "comfyui" },
      { label: "Stable Diffusion", schema: {}, value: "stable diffusion" },
    ],
    tts: [
      { label: "不使用", schema: {}, value: "none" },
      { label: "Genie TTS", schema: {}, value: "genie-tts" },
      { label: "GPT SoVITS", schema: {}, value: "gpt-sovits" },
      { label: "IndexTTS", schema: {}, value: "index-tts" },
      { label: "CosyVoice", schema: {}, value: "cosyvoice" },
    ],
  },
  api_config: {
    gpt_sovits_api_path: "",
    gpt_sovits_url: "http://127.0.0.1:9880",
    tts_provider: "gpt-sovits",
    tts_speed: 1,
    tts_split_enabled: false,
    tts_max_sentence_length: 15,
    t2i_provider: "comfyui",
    t2i_work_path: "",
    t2i_api_url: "http://127.0.0.1:8188",
    t2i_default_workflow_path: "",
    t2i_prompt_node_id: "6",
    t2i_output_node_id: "9",
    llm_api_key: { Deepseek: "" },
    llm_base_url: "https://api.deepseek.com/v1",
    llm_model: {},
    llm_provider: "Deepseek",
    is_streaming: true,
    temperature: 0.7,
    repetition_penalty: 1,
    presence_penalty: 0,
    frequency_penalty: 0,
    max_context_tokens: 128000,
    compact_threshold: 0.4,
    compact_target_ratio: 0.3,
    history_recent_messages: 20,
    max_tool_result_chars: 6000,
    max_active_tool_groups: 3,
    hugging_face_access_token: "",
    llm_extra_configs: {},
    tts_extra_configs: {},
    asr_extra_configs: {},
    t2i_extra_configs: {},
  },
  background_list: [
    {
      name: "默认房间",
      sprite_prefix: "room",
      sprites: [{ path: "/assets/system/picture/shinsekai.png" }],
      bg_tags: "室内、默认、夜晚",
      bgm_list: ["data/bgm/room/quiet-night.mp3"],
      bgm_tags: "音乐 1：安静、夜晚\n",
    },
  ],
  characters: [
    {
      name: "Nanami",
      color: DEFAULT_CHARACTER_COLOR,
      sprite_prefix: "nanami",
      sprites: [
        {
          path: "/assets/present_example.png",
          voice_path: "data/speech/nanami/hello.wav",
          voice_text: "欢迎来到新世界。",
        },
      ],
      character_setting: "温柔、带一点调皮的剧情向角色。",
      sprite_scale: 1,
      emotion_tags: "立绘 1：默认、微笑、惊讶\n",
      speech_speed: 1,
      speech_volume: 1,
      prompt_text: "欢迎来到新世界。",
      prompt_lang: "ja",
      pronunciation_map: { Nanami: "ななみ" },
    },
  ],
  system_config: {
    base_font_size_px: 56,
    ui_language: "zh_CN",
    voice_language: "ja",
    asr_provider: "vosk",
    asr_language: "",
    asr_whisper_model_size: "small",
    asr_whisper_device: "auto",
    asr_whisper_compute_type: "",
    music_volumn: 30,
    theme_color: "#d4788e",
    bgm_path: "",
    background_path: "",
    live_room_id: "",
    chat_window_geometry_b64: "",
    chat_ui_theme_path: "",
    chat_ui_runtime_mode: "react",
    music_cover_work_dir: "./data/music_cover",
    music_cover_yt_dlp_exe: "",
    music_cover_ffmpeg_exe: "",
    music_cover_uvr_cmd_template: "",
    music_cover_rvc_cmd_template: "",
    music_cover_rvc_model_path: "",
    music_cover_rvc_index_path: "",
    music_cover_rvc_device: "cuda:0",
    music_cover_rvc_model_version: "v2",
    music_cover_rvc_f0_method: "rmvpe",
    music_cover_rvc_pitch: 0,
    music_cover_rvc_index_rate: 0.75,
    music_cover_rvc_filter_radius: 3,
    music_cover_rvc_resample_sr: 0,
    music_cover_rvc_rms_mix_rate: 0.25,
    music_cover_rvc_protect: 0.33,
  },
};

export const sampleTemplates: TemplateSummary[] = [
  {
    id: "default",
    name: "默认叙事模板",
    path: "./data/character_templates/default.txt",
    updatedAt: "preview",
    content: "你正在和 {{characters}} 进行一场沉浸式对话。",
  },
];

export const samplePlugins: PluginManifest[] = [
  {
    author: "Shinsekai",
    id: "core-tools",
    directory: "plugins/core_tools",
    entry: "plugins.core_tools.plugin:CoreToolsPlugin",
    title: "内置工具",
    enabled: true,
    loaded: true,
    version: "built-in",
    description: "角色、记忆和文件工具。",
    permissions: ["tools"],
    settingsPages: [],
    slots: ["settings-tools"],
    toolsTabs: ["内置工具"],
  },
];

export const samplePluginCatalog: PluginCatalogItem[] = [
  {
    author: "Shinsekai",
    commitSha: "4aa82f9preview",
    displayName: "Vision Demo",
    downloadUrl: "https://r2.example.invalid/plugins/vision-demo/1.2.0/vision-demo.zip",
    description: "示例视觉理解插件，演示发现页、下载状态和安装进度。",
    downloaded: false,
    entry: "vision_demo.plugin:VisionDemoPlugin",
    forks: 2,
    id: "vision-demo",
    installed: false,
    name: "视觉理解示例",
    packageR2Key: "plugins/vision-demo/1.2.0/vision-demo.zip",
    packageSha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    packageSize: 524288,
    packageSource: "r2",
    packageUrl: "https://r2.example.invalid/plugins/vision-demo/1.2.0/vision-demo.zip",
    repo: "RachelForster/Shinsekai-Vision-Demo",
    securityScan: { bandit: { pass: true }, pip_audit: { pass: true } },
    sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    lowestShinsekaiVersion: ">=0.2.0",
    shortDescription: "Official R2 package preview with checksum metadata.",
    size: 524288,
    stars: 12,
    tags: ["vision", "demo", "official"],
    updatedAt: "2026-06-06T00:00:00Z",
    version: "1.2.0",
  },
  {
    author: "Community",
    description: "示例 ASR 适配器，浏览器预览不会访问真实网络。",
    downloaded: true,
    entry: "whisper_asr.plugin:WhisperAsrPlugin",
    installed: false,
    name: "Whisper ASR",
    repo: "RachelForster/Shinsekai-Whisper-ASR",
  },
];

export const sampleMcpConfig: McpConfig = {
  default_call_timeout: 300,
  enabled: true,
  path: "data/config/mcp.yaml",
  servers: [
    {
      enabled: true,
      name_prefix: "demo_",
      transport: "sse",
      url: "http://127.0.0.1:8765/sse",
    },
  ],
};

export const sampleMcpTools: McpToolPreview[] = [
  {
    description: "浏览器预览中的 MCP 工具。",
    name: "search",
    prefix: "demo_",
    registered_name: "demo_search",
  },
];

export const sampleChatSnapshot: ChatSnapshot = {
  backgroundPath: "",
  characterName: "Nanami",
  dialogText: "欢迎来到新世界。这里是 React 舞台预览，真实聊天事件会从 platform adapter 进入状态机。",
  historyEntries: [
    { id: "history-0", role: "system", text: "旁白: 欢迎来到新世界。" },
    { id: "history-1", revertUserIndex: 0, role: "user", text: "你: 你好，Nanami。" },
    { id: "history-2", role: "assistant", text: "Nanami: 欢迎来到新世界。" },
  ],
  historyPath: "./data/chat_history/preview.json",
  inputDraft: "",
  numericInfo: "idle",
  options: ["继续", "查看历史", "切换角色"],
  runtimeMode: "react",
  sprites: [{ id: "nanami-default", path: "/assets/present_example.png", label: "Nanami" }],
  status: "idle",
  voiceLanguage: "ja",
};

export const sampleChatTheme: ChatThemePayload = {
  raw: {
    dialog_label: {
      extra_qss: "background-color: rgba(50,50,50,200); border-color: rgba(255,255,255,85); border-radius: 8px;",
    },
    dialog_offset_y: 0,
    dialog_padding: 32,
    dialog_width_pct: 86,
    option_row: {
      extra_qss: "background-color: rgba(50,50,50,175); border-color: rgba(255,255,255,70);",
      hover_extra_qss: "background-color: rgba(80,80,80,210);",
    },
    options_gap: 10,
  },
  themeColor: "rgba(50,50,50,200)",
};

export const sampleChatThemeManifests: Record<string, ChatThemeManifest> = {
  "classic-dark": {
    schema: 1,
    id: "classic-dark",
    name: { zh_CN: "经典暗色", en: "Classic Dark", ja: "クラシック・ダーク" },
    author: "Shinsekai",
    version: "1.0.0",
    description: {
      zh_CN: "默认深色主题，半透明对话框",
      en: "Default dark theme with a translucent dialog box",
    },
    tokens: {
      global: { themeColor: "#644ae3" },
      dialog: {
        background: "rgba(20,20,28,0.86)",
        borderColor: "rgba(255,255,255,0.32)",
        borderRadius: "8px",
        color: "#ffffff",
        padding: 40,
        widthPct: 86,
        offsetY: 0,
        boxShadow: "0 16px 44px rgba(0,0,0,0.5)",
      },
      options: {
        background: "rgba(50,50,50,0.68)",
        borderColor: "rgba(255,255,255,0.28)",
        color: "#ffffff",
        gap: 10,
        hover: { background: "rgba(70,70,70,0.74)" },
      },
      input: {
        background: "rgba(34,34,40,0.9)",
        borderColor: "rgba(255,255,255,0.22)",
        fieldBackground: "rgba(50,50,50,0.78)",
        color: "#ffffff",
      },
      toolbar: {
        background: "rgba(34,34,40,0.9)",
        borderColor: "rgba(255,255,255,0.22)",
        color: "#ffffff",
      },
      send: { background: "#644ae3", color: "#ffffff" },
      name: { color: "#9c8cff" },
      logs: {
        page: { color: "#f7f3ff" },
        panel: {
          background: "rgba(20,20,28,0.78)",
          borderColor: "rgba(255,255,255,0.16)",
          borderRadius: "8px",
          boxShadow: "0 18px 36px rgba(0,0,0,0.22)",
          color: "#f7f3ff",
        },
        toolbar: { background: "rgba(26,26,36,0.9)", borderColor: "rgba(255,255,255,0.16)", color: "#f7f3ff" },
        sidebar: { background: "rgba(18,18,26,0.84)", borderColor: "rgba(255,255,255,0.14)", color: "#f7f3ff" },
        source: { background: "rgba(100,74,227,0.14)", borderColor: "rgba(156,140,255,0.44)", color: "#cfc7ff" },
        viewer: { background: "rgba(12,12,18,0.82)", borderColor: "rgba(255,255,255,0.14)", color: "#f7f3ff" },
        code: {
          background: "rgba(8,9,14,0.9)",
          color: "#f3f0ff",
          fontFamily: "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
        },
        line: {
          borderColor: "rgba(255,255,255,0.08)",
          expanded: { background: "rgba(100,74,227,0.15)" },
          hover: { background: "rgba(100,74,227,0.1)" },
        },
        number: { borderColor: "rgba(255,255,255,0.1)", color: "rgba(226,220,255,0.5)" },
        detail: { background: "rgba(255,255,255,0.05)", borderColor: "rgba(255,255,255,0.12)", color: "#e9e4ff" },
        badge: { background: "rgba(255,255,255,0.05)", borderColor: "rgba(255,255,255,0.12)", color: "rgba(239,235,255,0.72)" },
        event: { background: "rgba(100,74,227,0.16)", borderColor: "rgba(156,140,255,0.4)", color: "#cfc7ff" },
        fileItem: {
          background: "rgba(255,255,255,0.03)",
          borderColor: "rgba(255,255,255,0.1)",
          color: "#f7f3ff",
          active: { background: "rgba(100,74,227,0.18)", borderColor: "rgba(156,140,255,0.48)", color: "#d8d1ff" },
          hover: { background: "rgba(255,255,255,0.07)", borderColor: "rgba(255,255,255,0.18)" },
        },
        levels: {
          error: { background: "rgba(255,95,109,0.14)", borderColor: "rgba(255,95,109,0.48)", color: "#ff9ca7" },
          warn: { background: "rgba(237,168,64,0.13)", borderColor: "rgba(237,168,64,0.48)", color: "#f2c779" },
          info: { background: "rgba(64,196,141,0.12)", borderColor: "rgba(64,196,141,0.4)", color: "#8de0b9" },
          debug: { background: "rgba(91,173,255,0.1)", borderColor: "rgba(91,173,255,0.34)", color: "#9bcbff" },
          default: { background: "rgba(255,255,255,0.05)", borderColor: "rgba(255,255,255,0.12)", color: "rgba(239,235,255,0.72)" },
        },
      },
      typewriter: { cps: 40 },
    },
  },
  "light-paper": {
    schema: 1,
    id: "light-paper",
    name: { zh_CN: "浅色纸张", en: "Light Paper", ja: "ライトペーパー" },
    author: "Shinsekai",
    version: "1.0.0",
    description: {
      zh_CN: "明亮纸张风格，适合白天",
      en: "Bright paper-like theme for daytime",
    },
    tokens: {
      global: { themeColor: "#c77dff" },
      dialog: {
        background: "rgba(250,248,244,0.92)",
        borderColor: "rgba(0,0,0,0.16)",
        borderRadius: "12px",
        color: "#2a2730",
        padding: 36,
        widthPct: 82,
        offsetY: 0,
        boxShadow: "0 12px 36px rgba(0,0,0,0.18)",
      },
      options: {
        background: "rgba(255,255,255,0.86)",
        borderColor: "rgba(0,0,0,0.14)",
        color: "#2a2730",
        gap: 10,
        hover: { background: "rgba(240,236,250,0.94)" },
      },
      input: {
        background: "rgba(255,255,255,0.9)",
        borderColor: "rgba(0,0,0,0.14)",
        fieldBackground: "rgba(255,255,255,0.96)",
        color: "#2a2730",
      },
      toolbar: {
        background: "rgba(255,255,255,0.9)",
        borderColor: "rgba(0,0,0,0.14)",
        color: "#2a2730",
      },
      send: { background: "#c77dff", color: "#ffffff" },
      name: { color: "#9d4edd" },
      logs: {
        page: { color: "#2a2730" },
        panel: {
          background: "rgba(255,255,255,0.88)",
          borderColor: "rgba(66,50,92,0.14)",
          borderRadius: "8px",
          boxShadow: "0 14px 32px rgba(75,55,110,0.1)",
          color: "#2a2730",
        },
        toolbar: { background: "rgba(255,255,255,0.92)", borderColor: "rgba(66,50,92,0.14)", color: "#2a2730" },
        sidebar: { background: "rgba(255,255,255,0.82)", borderColor: "rgba(66,50,92,0.12)", color: "#2a2730" },
        source: { background: "rgba(199,125,255,0.12)", borderColor: "rgba(157,78,221,0.28)", color: "#7930b2" },
        viewer: { background: "rgba(255,255,255,0.9)", borderColor: "rgba(66,50,92,0.14)", color: "#2a2730" },
        code: {
          background: "rgba(253,251,255,0.95)",
          color: "#302a3a",
          fontFamily: "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
        },
        line: {
          borderColor: "rgba(66,50,92,0.1)",
          expanded: { background: "rgba(199,125,255,0.12)" },
          hover: { background: "rgba(199,125,255,0.08)" },
        },
        number: { borderColor: "rgba(66,50,92,0.1)", color: "rgba(42,39,48,0.48)" },
        detail: { background: "rgba(246,241,255,0.9)", borderColor: "rgba(66,50,92,0.12)", color: "#302a3a" },
        badge: { background: "rgba(246,241,255,0.78)", borderColor: "rgba(66,50,92,0.12)", color: "rgba(42,39,48,0.66)" },
        event: { background: "rgba(199,125,255,0.14)", borderColor: "rgba(157,78,221,0.28)", color: "#7930b2" },
        fileItem: {
          background: "rgba(255,255,255,0.58)",
          borderColor: "rgba(66,50,92,0.12)",
          color: "#2a2730",
          active: { background: "rgba(199,125,255,0.14)", borderColor: "rgba(157,78,221,0.32)", color: "#7930b2" },
          hover: { background: "rgba(246,241,255,0.9)", borderColor: "rgba(157,78,221,0.22)" },
        },
        levels: {
          error: { background: "rgba(217,70,86,0.1)", borderColor: "rgba(217,70,86,0.3)", color: "#b42a3d" },
          warn: { background: "rgba(188,118,28,0.12)", borderColor: "rgba(188,118,28,0.34)", color: "#985f16" },
          info: { background: "rgba(38,141,101,0.1)", borderColor: "rgba(38,141,101,0.28)", color: "#217a58" },
          debug: { background: "rgba(47,116,190,0.1)", borderColor: "rgba(47,116,190,0.26)", color: "#2f6eae" },
          default: { background: "rgba(246,241,255,0.78)", borderColor: "rgba(66,50,92,0.12)", color: "rgba(42,39,48,0.66)" },
        },
      },
      typewriter: { cps: 36 },
    },
  },
};

export const sampleChatThemeSummaries: ChatThemeSummary[] = Object.values(sampleChatThemeManifests).map((manifest) => ({
  id: manifest.id,
  name: manifest.name,
  author: manifest.author,
  version: manifest.version,
  source: "builtin",
}));

export const sampleLastLaunch: ChatLaunchPayload = {
  backgroundName: "默认房间",
  characters: ["Nanami"],
  historyPath: "",
  templateId: "default",
};
