"""Application-level story project loading and orchestration."""

from .idempotency import (
    StoryCommandConflictError,
    StoryCommandIdempotencyIndex,
    StoryCommandRecord,
    story_command_payload_hash,
)
from .project_loader import StoryProjectLoader, load_story_project
from .coordinator import start_or_recover_story_session, story_snapshot_patch
from .characters import (
    ActorContext,
    CastChangeRequestError,
    CharacterImportTokenStore,
    CharacterLoadPhase,
    CharacterProfile,
    CharacterReadinessError,
    CharacterResolutionError,
    CharacterResourceManager,
    CharacterSourceResolver,
    ConfigCharacterLibrary,
    NoopCharacterPresentationAdapter,
    StoryCastApplicationService,
    materialize_imported_character,
    migrate_selected_characters,
)
from .persistence import (
    GlobalStoryProgress,
    JsonGlobalStoryProgressStore,
    JsonStorySessionRepository,
    StoryPersistenceError,
    StoryProgramMismatchError,
)
from .session import StoryBranch, StorySession, StorySessionAck
from .scene import (
    AuthorContext,
    CastSelectionContext,
    ConfigSceneModel,
    SceneContextBuilder,
    SceneDialogueItem,
    SceneOrchestrator,
    SceneProtocolError,
    SceneTurnResult,
    ValidatedCastPlanner,
)

__all__ = [
    "StoryCommandConflictError",
    "StoryCommandIdempotencyIndex",
    "StoryCommandRecord",
    "StoryBranch",
    "StorySession",
    "StorySessionAck",
    "GlobalStoryProgress",
    "JsonGlobalStoryProgressStore",
    "JsonStorySessionRepository",
    "StoryPersistenceError",
    "StoryProgramMismatchError",
    "start_or_recover_story_session",
    "story_snapshot_patch",
    "ActorContext",
    "CastChangeRequestError",
    "CharacterImportTokenStore",
    "CharacterLoadPhase",
    "CharacterProfile",
    "CharacterReadinessError",
    "CharacterResolutionError",
    "CharacterResourceManager",
    "CharacterSourceResolver",
    "ConfigCharacterLibrary",
    "NoopCharacterPresentationAdapter",
    "StoryCastApplicationService",
    "materialize_imported_character",
    "migrate_selected_characters",
    "ConfigSceneModel",
    "AuthorContext",
    "CastSelectionContext",
    "SceneContextBuilder",
    "SceneDialogueItem",
    "SceneOrchestrator",
    "SceneProtocolError",
    "SceneTurnResult",
    "ValidatedCastPlanner",
    "StoryProjectLoader",
    "load_story_project",
    "story_command_payload_hash",
]
